filter:
    excluded_paths:
        - "tests/*"
        - ".atoum.php"
    dependency_paths:
        - "env/*"
        - "vendor/*"

before_commands:
    - "composer install"

tools:
    external_code_coverage:
        timeout: 600
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc: true
    php_cpd: false
